[system]
arch = "amd64"
os = "debian"
file_type = "deb"

[packages]
# syntax is
#   [packages.{repo}]
#   arch = "{arch}"
#   file_type = "{filetype}"
#   user = "{user}"
#   repo = "{repo}"
#   get_package = true/false
#   get_source = true/false
# arch and filetype are matched by regex, so should be flexible as seen below

  [packages.vscodium]
  arch = "amd64"
  file_type = "deb"
  user = "VSCodium"
  repo = "vscodium"
  get_source = true

  [packages.atom]
  arch = "amd64"
  file_type = "deb"
  user = "atom"
  repo = "atom"
  get_package = false
  get_source = true

  [packages.keepassxc]
  arch = "x86_64"
  file_type = "AppImage"
  user = "keepassxreboot"
  repo = "keepassxc"
  get_package = false
  get_source = true

  [packages.neovim]
  arch = "linux64"
  file_type = "tar.gz"
  user = "neovim"
  repo = "neovim"
  get_package = false
  get_source = true